[build]
  functions = "netlify/functions"
  command = "npm run server"

[dev]
  functions = "netlify/functions"
  command = "npm run server"

[functions]
  external_node_modules = ["express", "serverless-http", "cors", "node-fetch"]
  node_bundler = "esbuild"